name: render

on:
  schedule:
  - cron: "0 */6 * * *"
  push:
    branches: master

jobs:
  render:
    runs-on: ubuntu-latest
    container: sudosk/covid19-dashboard:latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      #- uses: r-lib/actions/setup-r@v1
      #- uses: r-lib/actions/setup-pandoc@v1

      - name: Render in the container
        run: |
          Rscript render.R
      
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GIT_CONFIG_NAME: sudosk
          GIT_CONFIG_EMAIL: to.sangramkeshari@gmail.com
          GITHUB_TOKEN: ${{ secrets.TK2 }}
          BRANCH: gh-pages
          FOLDER: .
